apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
spec:
  storageClassName: nfs
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
 # persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /mnt/data/k0s
    server: 192.168.68.3
    readOnly: false
  persistentVolumeReclaimPolicy: Retain
